// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTgEtvpl2xkIr4hQPsWkCvKxGlzr6epso',
    appId: '1:283704459158:android:ad732e2ad01ca52891a7b7',
    messagingSenderId: '283704459158',
    projectId: 'test-7fe47',
    storageBucket: 'test-7fe47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4JPxPXrNCqPvwNi746mBUoex0qJirww',
    appId: '1:283704459158:ios:b3cf8d4d7dd5869691a7b7',
    messagingSenderId: '283704459158',
    projectId: 'test-7fe47',
    storageBucket: 'test-7fe47.appspot.com',
    androidClientId: '283704459158-mjskm230pb45tngeifj9rvapt22c1953.apps.googleusercontent.com',
    iosClientId: '283704459158-1m0foj6b2p56199emnfb0lgg1qg4f92i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonor',
  );
}
